SELECT TOP (1000) [Account_id]
      ,[Customer_id]
      ,[Account_type]
      ,[Date_opened]
      ,[Account_other_details]
  FROM [dbo].[Account]

  SELECT TOP (1000) [Customer_id]
      ,[Customer_name]
      ,[Customer_email]
      ,[Customer_password]
      ,[Customer_address]
      ,[Customer_other_details]
  FROM [dbo].[customer]
